name: base_flutter
description: Base Project By Diego GV.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  http: ^0.13.4
  flutter_secure_storage: ^5.0.2
  http_interceptor: ^1.0.2
  objectbox: ^1.5.0
  objectbox_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  objectbox_generator: any

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
      - logo_iesoluciones.png

  fonts:
      - family: GrapeNuts
        fonts:
          - asset: fonts/GrapeNuts-Regular.ttf
      #       - asset: fonts/Schyler-Italic.ttf
      #         style: italic
      - family: OpenSans
        fonts:
          - asset: fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
          - asset: fonts/OpenSans-VariableFont_wdth,wght.ttf

      - family: BebasNeue
        fonts:
          - asset: fonts/BebasNeue-Regular.ttf
    #         weight: 700
